# Generated by Django 5.2 on 2025-04-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_configuration_systemprompt_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
